### ISSUE TITLE
About user profile attributes

### ISSUE THREAD

**Issue by softwareklinic** [actionml/template-scala-parallel-universal-recommendation#11]
Let us say we have users whose profile might have attributes such as DeviceName, Brandname, PhonePlan, Tenure, Birthdate etc.. and we have ITEMS that could be URLs (links on the page) -- with properties such as Category (e.g. phone, tablets, etc...)...

How do you propose we construct our data ingestion and engine.json... Can the data be as below e.g.

10000001, view, http://www.xxxxxx.com 
http://www.xxxxxxxx.com, $set, Categories: phone
10000001, $set, Tenure: 3 years
10000001, $set, DeviceName: iPhone
10000001, $set, DeviceBrandName: Apple

Will the UR Algorithm consider the $set attributes we set using $set in the recommendation?

**Comment by softwareklinic** [comment]
We have data for both ITEMs and USERs as below...

Items - are URLs viewed
Users - have attributes such as tenure, birthyear, brandname, devicename, plan

If we ingest events such as below

u1, view, http://www.url1.com
u2, view, http://www.url1.com
u3, view, http://www.url2.com
http://www.url1.com, $set, categories:billing
http://www.url2.com, $set, categories:payment
u1, $set, tenure:3+years
u1, $set, birthyear, 1972
u2, $set, tenure:1+year
u2, $set, birthyear: 1980

Assume we ingest 100s of such combinations...

If we ingest data this way -- if I want to recommend top 3 urls for any given user... does the UNIVERSAL RECOMMENDER template consider the user attributes... during the decision making... or does it just consider the item attributes only...

We didnt see much impact of the user attributes when trying out this way... so we want and used another alternative.... means --- marking each attribute as a event by itself as below... which seems to be working... but i want to understand how does the template use user properties/attributes...

u1, view, http://www.url1.com
u2, view, http://www.url1.com
u3, view, http://www.url2.com
u1, tenure, 3+years
u1, birthdyear, 1972
u1, tenure, 1+year
u2, birthyear, 1980
http://www.url1.com, $set, categories:billing
http://www.url2.com, $set, categories:payment

**Comment by thesuperzapper** [comment]
"BUMP"

**Comment by pferrel** [comment]
Better to ask questions on the Google group here: https://groups.google.com/forum/#!forum/actionml-user

I've answered this several times on the group and the predictionio-user group. Check this thread https://groups.google.com/d/msgid/actionml-user/5D3BE0CE-C744-4E1E-97E0-336920F1BDFE%40occamsmachete.com?utm_medium=email&utm_source=footer

basically only items have usable properties and they must be arrays of strings, not as above--a single value. A single value is fine but must be encoded as an array of one value,

User properties must be encoded as "indicator" events, similar to usage events. See the thread for location example.
