### ISSUE TITLE
Priorize recent itens

### ISSUE THREAD

**Issue by bratao** [actionml/template-scala-parallel-universal-recommendation#17]
Hello, 

Thanks for this awesome project !
Do it have any mechanism to boost recent items ?
I need to apply to recommend something like a timeline, and recent items should have the preference.

**Comment by pferrel** [comment]
Support forums here: https://groups.google.com/forum/#!forum/actionml-user

Yes, you can use any number of the most recent events in user history for calculating recommendations, without altering how many are used to calculate the model. This captures "recent user intent"
